# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        make install

    - name: Run Linting
      run: |
        pip install flake8
        flake8 app.py

    - name: Start Application
      run: |
        nohup make run &
        sleep 5
        curl -f http://localhost:3000 || exit 1

    - name: Stop Application
      run: |
        pkill -f "python app.py"
